### ISSUE TITLE
View app logs from cli

### ISSUE THREAD

**Issue by hjyoung1** [caprover/caprover-cli#50]
Option to check app logs from cli would be great.
Because for some reason web panel doesn't always work.

**Comment by githubsaturn** [comment]
@hjyoung1 
This has been discussed in the past. We decided to avoid doing this due to the limitations that it has compared to the real log. We gave this feature on the web client because there's no alternative way to get the logs in you're remote on a browser. 


However, if you have access to the terminal, ssh command is the preferred way to get the logs.

**Comment by githubsaturn** [comment]
All you need to do is to run
```
ssh root@captain.your.domain.com 'docker service logs srv-captain--yourappnamehere --since 10m --follow'
```
This will display the logs for the past 10 minutes. If you want it to exit immediately, just remove `--follow` flag. As you can see, there is no point behind adding a log to the CLI.
