### ISSUE TITLE
Private npm modules

### ISSUE THREAD

**Issue by skiv71** [caprover/caprover-cli#63]
Hi, I've looked, but been unable to find out how to get similar functionality to what heroku provides. Namely, to use a .npmrc and be able to access private registry modules. Bit of a deal breaker. Thanks

**Comment by githubsaturn** [comment]
I am assuming you have a nodejs application which is using some private modules. If that's right, then read on.

CapRover build process is just a Docker build process. So in order to build your application with some private modules:

1)
You need to add a file called `.npmrc` with this content:
```
//registry.npmjs.org/:_authToken=${NPM_TOKEN}
```
Make sure the name is correct, it starts with a dot, and also make sure the file is committed to your repository.

2)
Create a `Dockerfile` with this content:
```
FROM node:14-alpine

RUN apk update && apk upgrade && \
    apk add --no-cache git
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY .npmrc .npmrc  
COPY ./package*.json /usr/src/app/

RUN npm install --production && npm cache clean --force
RUN rm -f .npmrc

COPY ./ /usr/src/app
ENV NODE_ENV production
ENV PORT 80
EXPOSE 80

CMD [ "npm", "start" ]
```

3)
Make sure you add an environmental variable called `NPM_TOKEN` to your app's env var list with the right token.


You can read more about this here: https://docs.npmjs.com/docker-and-private-modules
