### ISSUE TITLE
Setup issue with DNS for Caprover

### ISSUE THREAD

**Issue by rishiosaur** [caprover/caprover-cli#71]
Hi!

I've been working on hosting my own Caprover instance over at [o.rishi.cx](http://o.rishi.cx), and accessing it works perfectly—I've set up my DNS config properly too (you can check the MX records). However, I keep getting a `Verification Failed` error, even though it looks like everything's just fine on the outside. What can I do to fix this?

<img width="799" alt="image" src="https://user-images.githubusercontent.com/15793261/98448762-98a91f80-20fc-11eb-8633-0ce41f210fcc.png">

**Comment by rishiosaur** [comment]
@githubsaturn

**Comment by rishiosaur** [comment]
I think this might be a cache issue; that's the one thing I haven't tried out yet.

**Comment by rishiosaur** [comment]
Here's what my DNS records look like:

<img width="1045" alt="image" src="https://user-images.githubusercontent.com/15793261/98448848-271da100-20fd-11eb-8f27-64e041f26278.png">

**Comment by rishiosaur** [comment]
Note: verification also isn't working through the web ui, so I think I might've set the dns wrong

**Comment by githubsaturn** [comment]
Who is your VPS provider? Do you have anything special with regards to your network config?

**Comment by rishiosaur** [comment]
@githubsaturn I'm running it using a reverse proxy on Raspberry pi; nothing out of the usual in terms of port forwarding

**Comment by githubsaturn** [comment]
I see. So yes, in that case the domain verification can fail. You need to make sure that `captain.o.rishi.cx` gets router to your rasberrypie if it's behind a NAT. You need to port forward 80/443 from your router to your RPie. When I visit `captain.o.rishi.cx` I see an nginx response which tells me the routing is not done right at your setup. You first need to be make sure the routing is done right. Then retry.

If the routing is done right, meaning that `captain.o.rishi.cx` points to your rasberry pie's CapRover page, and you still cannot verify your domain, then you can skip verification:
```
echo  "{\"skipVerifyingDomains\":\"true\"}" >  /captain/data/config-override.json
docker service update captain-captain --force
```

Note that this doesn't "fix" any routing problems if there is any. It just disables the extra verification that CapRover does. It is only useful if there is no problems other than CapRover not being able to verify its own domain - which can happen due to being behind a NAT/reverse proxy.
