### ISSUE TITLE
Error: self signed certificate

### ISSUE THREAD

**Issue by nixilb** [caprover/caprover-cli#78]
C:\Users\nisju\Downloads\node\node>caprover login

Login to a CapRover machine...

? CapRover machine URL address, it is "[http[s]://][captain.]your-captain-root.domain": https://captain.mydn.com
? CapRover machine password: [hidden]
? CapRover machine name, with whom the login credentials are stored locally: ooo

Something bad happened: cannot save ooo at https://captain.mydn.com.
Error: self signed certificate

**Comment by githubsaturn** [comment]
Steps to reproduce?

Did you use `caprover serversetup` to set up your instance?

self signed certificate error shows that you haven't enabled HTTPS on your instance, and are just forcefully redirecting to HTTPS. 

This combined with the other issue that you opened tells me that you haven't set up your instance correctly. 


Did you point A Record to your IP address? Is your VPS behind a router? 

- What is your actual domain? Is it `https://captain.mydn.com` ?

**Comment by nixilb** [comment]
mmh, did reset all, trying again.
(thanks for awesome support by the way).

**Comment by nixilb** [comment]
didn't reappear.

**Comment by codespearhead** [comment]
Duplicate of #672

In my case, I installed CapRover v.1.11.1 is via DigitalOcean one-click app and pointed a subdomain from CloudFlare to the vm IP.

As per the [documentation](https://caprover.com/docs/get-started.html#step-2-connect-root-domain), the CloudFlare Proxy and the fact that its free "certificate will [only] cover your zone apex (example.com) and _all first-level subdomains_".

Hence, disabling the CloudFlare Proxy and using the apex domain instead of a subdomain worked for me.
